-- MySQL Script generated by MySQL Workbench
-- 10/07/15 10:42:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payrollf2015
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payrollf2015
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payrollf2015` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `payrollf2015` ;

-- -----------------------------------------------------
-- Table `payrollf2015`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payrollf2015`.`Department` ;

CREATE TABLE IF NOT EXISTS `payrollf2015`.`Department` (
  `DepartmentID` INT NOT NULL,
  `DeptName` VARCHAR(45) NULL,
  `DeptHead` VARCHAR(45) NOT NULL,
  `DeptLocation` VARCHAR(45) NULL,
  `DeptContactEmail` DECIMAL(10,0) NULL,
  PRIMARY KEY (`DepartmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payrollf2015`.`Administrative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payrollf2015`.`Administrative` ;

CREATE TABLE IF NOT EXISTS `payrollf2015`.`Administrative` (
  `EmployeeID` INT NOT NULL,
  `EffectiveDate` DATE NOT NULL,
  `EmpStatus` VARCHAR(45) NULL,
  `DeptID` INT NOT NULL,
  `Department` VARCHAR(45) NULL,
  `Location` VARCHAR(255) NULL,
  `Supervisor` VARCHAR(45) NULL,
  `SupervisorID` INT NULL,
  `SalaryType` VARCHAR(1) NULL,
  `AnnualSalary` DOUBLE NULL,
  `HourlyRate` DOUBLE NULL,
  `PersonalOffDays` DOUBLE NULL,
  `VacationRate` DOUBLE NULL,
  `SickDays` DOUBLE NULL,
  `PayPeriodEnd` DATE NOT NULL,
  PRIMARY KEY (`EmployeeID`, `DeptID`),
  INDEX `fk_Administrative_Department1_idx` (`DeptID` ASC),
  CONSTRAINT `fk_Administrative_Department1`
    FOREIGN KEY (`DeptID`)
    REFERENCES `payrollf2015`.`Department` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payrollf2015`.`Personel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payrollf2015`.`Personel` ;

CREATE TABLE IF NOT EXISTS `payrollf2015`.`Personel` (
  `EmployeeID` INT NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `StreetAddress` VARCHAR(100) NULL,
  `City` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(45) NULL,
  `Telephone` DECIMAL(10,0) NULL,
  `EmergencyNum` DECIMAL(10,0) NULL,
  `DOB` DATE NULL,
  PRIMARY KEY (`EmployeeID`),
  INDEX `fk_Personel_Administrative_idx` (`EmployeeID` ASC),
  CONSTRAINT `fk_Personel_Administrative`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `payrollf2015`.`Administrative` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payrollf2015`.`Earnings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payrollf2015`.`Earnings` ;

CREATE TABLE IF NOT EXISTS `payrollf2015`.`Earnings` (
  `Admin_EmployeeID` INT NOT NULL,
  `Admin_DeprtID` INT NOT NULL,
  `PeriodPay_Beg` DATE NULL,
  `PeriodPay_End` DATE NULL,
  `RegularPay` DOUBLE NULL,
  `Overtime` DOUBLE NULL,
  `Bonus` DOUBLE NULL,
  `Other` DOUBLE NULL,
  PRIMARY KEY (`Admin_EmployeeID`, `Admin_DeprtID`),
  INDEX `fk_Earnings_Administrative1_idx` (`Admin_EmployeeID` ASC, `Admin_DeprtID` ASC),
  CONSTRAINT `fk_Earnings_Administrative1`
    FOREIGN KEY (`Admin_EmployeeID` , `Admin_DeprtID`)
    REFERENCES `payrollf2015`.`Administrative` (`EmployeeID` , `DeptID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payrollf2015`.`Hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payrollf2015`.`Hours` ;

CREATE TABLE IF NOT EXISTS `payrollf2015`.`Hours` (
  `Admin_EmployeeID` INT NOT NULL,
  `Admin_DeptID` INT NOT NULL,
  `Month15_Hrs` INT NULL,
  `Month30_Hrs` INT NULL,
  PRIMARY KEY (`Admin_EmployeeID`),
  CONSTRAINT `fk_table1_Administrative1`
    FOREIGN KEY (`Admin_EmployeeID` , `Admin_DeptID`)
    REFERENCES `payrollf2015`.`Administrative` (`EmployeeID` , `DeptID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payrollf2015`.`YearToDate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payrollf2015`.`YearToDate` ;

CREATE TABLE IF NOT EXISTS `payrollf2015`.`YearToDate` (
  `Admin_EmployeeID` INT NOT NULL,
  `Admin_DeprtID` INT NOT NULL,
  `PeriodPay_Beg` DATE NULL,
  `PeriodPay_End` DATE NULL,
  PRIMARY KEY (`Admin_EmployeeID`, `Admin_DeprtID`),
  CONSTRAINT `fk_YearToDate_Earnings1`
    FOREIGN KEY (`Admin_EmployeeID` , `Admin_DeprtID`)
    REFERENCES `payrollf2015`.`Earnings` (`Admin_EmployeeID` , `Admin_DeprtID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payrollf2015`.`Deductions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payrollf2015`.`Deductions` ;

CREATE TABLE IF NOT EXISTS `payrollf2015`.`Deductions` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
